# Generated by Django 5.1.7 on 2025-03-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kblog',
            new_name='TBKblog',
        ),
    ]
