# Generated by Django 5.1.7 on 2025-03-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kblog', '0002_rename_kblog_tbkblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TBKblog',
            new_name='Kblog',
        ),
    ]
